.gitignore, app.go, geo/geometry.go
Implemented features:
1. Tile factory method
2. Tile.Contains(lat, lon)
3. Tile.Degrees2Pixels(lat, lon)
=> Implemented basic coordinate maths.

.travis.yml, app.go, database/database.go, geo/geometry.go, mapobjects/object.go, mapobjects/tile.go, mapobjects/tile_test.go, svg/svg.go
I've added a linter in the build and fixed all style issues
=> Add linter into the build

app.go, database/database.go, geo/geometry.go, mapobjects/object.go, svg/specialObjects.go, svg/svg.go
All rendering functions are hardcoded for a while.
=> Feature: now TMS can render a complex objects from a database

.gitignore, app.go, config.toml, database/database.go, geo/geometry.go
Now we have BaseGeometry like that:
```go
type BaseGeometry struct {
ID     int
TypeID int
Value  string
Attrs  []BaseAttribute
}
```
=> Add attributes into BaseGeometry objects

.gitignore, app.go, config.sample.toml, database/entities/object.go, listeners/listeners.go, settings/manager.go, settings/styling/primitives/image.go, settings/styling/primitives/text.go, settings/styling/read.go, settings/styling/style.go, style-samples/home.toml, style-samples/mil/airbase.toml, tiles/rendering.go, utils/files.go
It is able to read basic styles from file system now and render text primitives.
It is definitely not the final code. It will be refactored and rewritten in some places.
=> Reading styles from file system [WIP]

database/database.go, listeners/listeners.go, settings/styling/primitives/image.go, settings/styling/primitives/text.go, settings/styling/style.go, style-samples/home.toml, utils/image.go
- cache external images;
- render geo objects only of a tile contains these objects
- add ability to set image format (image/png, image/svg+xml, etc)
- align images in a "Image" primitive
=> Improve image rendering

database/database.go, utils/image.go
Use ST_Intersects instead of ST_Contains. ST_Intersects is much faster.
=> Improve performance of tile rendering

tiles/rendering.go
Size arrow and translating degrees to pixels were fixed. Image rendering of a patrolling area’s and aviation flight’s positions were changed
=>  Fix some issues with MultiString rendering

database/database.go, database/entities/object.go, settings/styling/primitives/image.go, tiles/rendering.go
Now each MapObject has new fields IsAntenna, NeedShowAzimuthalGrid, BeamWidth, Sidelobes, wich need for rendering beam diagram. Method for rendering beam diagram was added.
=> Add rendering beam diagram

tiles/rendering.go, utils/image.go
Calculation coordinates for beam diagram was fixed. For cross-platform path filepath.FromSlash are using.
=> Fixed some issue of calculation coordinates for beam diagram

database/database.go, database/entities/object.go, tiles/rendering.go
Rendering beam diagram was separated from azimuthal grid.
Rendering beam diagram depends from field NeedShowDirectionalDiagram.
=> Rules for rendering of beam diagram were changed.

listeners/listeners.go, tiles/bbox.go, tiles/bbox_test.go, tiles/tile.go
Add margin for bbox of a current tile to avoid "icon cropping" issue
=> Add margin for bbox of a tile

tiles/rendering.go
Rendering of image on route aviation flight was fixed. Now picture hase direction like route aviation flight's.
=> Fix some issues with rendering image on route aviation flight's.

settings/styling/primitives/image.go, tiles/rendering.go
Now angle of rotation of beam diagram and image are depend from field azimut.
=> Add rotation beam diagram and image

tiles/rendering.go
Rendering of 3 new objects were added: PlannedAttackMainDirection, CompletedProvideAction, AttackMainDirection. Now arrow of  route aviation flight are showing only at end.
=> Rendering of new special objects were added. Rendering route aviation flight was changed.

database/database.go, database/entities/object.go, listeners/listeners.go, tiles/rendering.go
Now rendering of special object use InnerColor and OutherColor from db. New type pit was added.
=> Rendering pit was added. InnerColor are used for rendering arrow.

.gitignore, database/entities/object.go, settings/manager.go, tiles/rendering.go, utils/image.go
Now MapObject has new field - Hash. When hash will been changed images for route aviation flight and patrolling area will been updated.
=> add updating images if hash changed

tiles/rendering.go
Now we aren't using local images for rendering route aviation flight. These images are downloded from server
=> Image for route aviation flight, patrolling area download from server

.gitignore, database/database.go, tiles/rendering.go
Now route aviation flight, patrolling area and pit are rendered as curve. Hatching was added along pit as curve. Some methods were refactored. 	Getting objects from db via situation_id was fixed.
=> Change rendering linear objects

settings/styling/primitives/image.go, tiles/rendering.go
When mirror reflection was applied to selected object then with him rotated and other objects.
=> fixed some issue with mirror reflection

database/database.go, database/entities/object.go, settings/styling/primitives/image.go, tiles/rendering.go
Type MapObject was seporated to three type: MapObject, View, AzimuthalGrid. Refactoring. Add new field UseCurveBezier. Now line objects can rendering as polyline and curve. Now hatchings always are rednering on begin and end line.
=> Refactoring. Add new field UseCurveBezier
